apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-ddc-server
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: ss-ddc-server
  replicas: 1
  template:
    metadata:
      labels:
        app: ss-ddc-server
    spec:
      containers:
      - name: ss-ddc-server
        image: sundareshsas/sas-ddc-server:latest
        imagePullPolicy: Always
        ports:
        - name: https
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ss-ddc-service
  namespace: webapp
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ss-ddc-server

